name: macos_dock
description: "A Flutter widget that recreates the macOS dock with smooth scaling animations, hover effects, and customizable parameters for a native-like experience."
version: 1.0.1
homepage: https://github.com/master-wayne7/macos_dock

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

example: main.dart

flutter:
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
funding:
  - https://www.buymeacoffee.com/ronitrameja
