name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2.14.0
        with:
          channel: "stable"
      - run: |
          cd example
          flutter config --enable-web
          flutter pub get
          flutter build web --base-href /macos_dock/tree/gh-pages/ --release
      - run: |
          cd example/build/web
          git init
          git config --global user.email ronitrameja28@gmail.com
          git config --global user.name ronit
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/master-wayne7/macos_dock.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
